.github/config.yml

Signed-off-by: crustyy <muskanbansal919@gmail.com>
This PR fixes #5
- [O] Yes, I signed my commits.

welcome bot showing celebration img

---

.github/release-drafter.yml

Signed-off-by: anita-ihuman <charlesanita403@gmail.com>

added release drafter  for this repository

---

apinighthawk/nighthawk.go
cmd/main.go

Signed-off-by: Kush Trivedi <kushthedude@gmail.com>
This PR fixes #15 

fix: golangci-lint issues in files

---

.github/workflows/ci.yml
.gitignore
ci/build.sh

Signed-off-by: Kush Trivedi <kushthedude@gmail.com>
This PR fixes #20 
- This will be a 3-step process

 feat: build nighthawk in ci, add nighthawk assets

---

.github/workflows/ci.yml
apinighthawk/nighthawk.go

Signed-off-by: Kush Trivedi <kushthedude@gmail.com>
This PR fixes #23 

fix: run nighthawk through binary

---

docs/Gemfile
docs/Gemfile.lock
docs/_config.yml

[Site] Inclusion of `plugins` in _config.yaml

---

.github/ISSUE_TEMPLATE/site_update.md

Added site_update.md ISSUE_TEMPLATE

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/site_update.md

This PR fixes #47 
- Adding a new section "Contributor Resources" at the end of each template.
- Updating the "Contributing.md" link
to ` https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md`
from `https://github.com/layer5io/getnighthawk`
Please Revert, if any other changes required.

Update issue templates

---

.github/workflows/slack.yml

Signed-off-by: Ruth-ikegah <ruthikegah@gmail.com>
I updated the slack.yaml file to reflect current repository name 
This PR fixes #32

updated repo name

---

docs/_sass/getnighthawk.scss
docs/index.html

This PR addresses the issue of cleaning up the home page and updating changes that caused it to look messy.
This PR fixes #53 

cleaned and updated the home page

---

CONTRIBUTING.md

Signed-off-by: Ruth-ikegah <ruthikegah@gmail.com>
I updated the Contributing file with Project description, a guide to building site locally and general contribution steps
This PR fixes #46 

Add Project description and contributing guide

---

docs/_sass/getnighthawk.scss
docs/index.html

Fixed the line spacing issue and alignment issues on the home page
This PR fixes #64 

reduce line spacings and alignment

---

docs/_sass/getnighthawk.scss
docs/index.html

Signed-off-by: vinayaksh42 <vinayaksh42@gmail.com>
This PR fixes #67 

para line space fix

---

.github/workflows/build-and-publish.yaml
action.yml

Signed-off-by: kumarabd <abishekkumar92@gmail.com>
- Build and release action for Getnighthawk release
- Action template and scripts initialised.

ci action template

---

docs/_data/navigation.yml
docs/_includes/footer.html
docs/_includes/header.html
docs/_sass/footer.scss
docs/_sass/getnighthawk.scss
docs/_sass/layout.scss
docs/_sass/navigation.scss

Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>
This PR fixes #35 

Added Navbar for GetNighthawk

---

.github/workflows/build-and-publish.yaml

Signed-off-by: kumarabd <abishekkumar92@gmail.com>

added docker build

---

docs/_data/footer.yml
docs/_includes/footer.html
docs/_sass/footer.scss

Updated the footer to bring down the copyright text and align them as discussed.

update the footer to bring down copyright text

---

docs/_data/footer-social.yml
docs/_data/footer.yml
docs/_includes/footer.html
docs/_sass/footer.scss

Changed the footer as per the SMP footer and brought the social-icons to the right of the copyright text.
This PR fixes #82 

update the footer

---

docs/_data/navigation.yml
docs/_includes/header.html
docs/_includes/navigation.html
docs/_sass/getnighthawk.scss
docs/_sass/layout.scss
docs/index.html

Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

Rectified Navbar & Some other views

---

README.md

Signed-off-by: Harshita-Kanal <harshita.kgv@gmail.com>
This PR fixes #104
Updated README

[README] Update README Community Section

---

pkg/client/transform.go

Signed-off-by: kumarabd <abishekkumar92@gmail.com>
This PR fixes https://github.com/layer5io/meshery/issues/2912

bug fixe for nil pointer

---

docs/_sass/getnighthawk.scss
docs/_sass/layout.scss
docs/index.html

Background color was different than desired color
Changed background color of header and main div
This PR fixes #110

changed background color

---

CONTRIBUTING-gitflow.md

Signed-off-by: Ayush <ayushkhandelwal3217@gmail.com>
Small changes to workflow document.
This PR fixes #118 

git flow doc updated

---

docs/_sass/getnighthawk.scss

Added Hover Effect on buttons
https://user-images.githubusercontent.com/58226527/120430347-82162e80-c394-11eb-8acf-7be82ba9a34e.mp4
This PR fixes #122 
The previous PR, was showing an error even it was committed with --signoff. So I created a new PR as @vinayaksh42 suggested.

[Site] Hover Effect on Buttons --signoff

---

docs/_includes/faq.html
docs/_includes/stewarded.html
docs/index.html

Link fix for buttons!

---

docs/_sass/faq.scss

Updated faq color and style as in the Figma design
This PR fixes #124 
@JubayerJoy Can you please confirm the changes so I can work on the " The sidebar of Getnighthawk Docs " section too? Thank you.

[Site] Change color and style of menu items --signoff

---

docs/_sass/footer.scss
docs/_sass/getnighthawk.scss
docs/_sass/mailing-list.scss

Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>
Fixed the padding and margins.
This PR fixes #123 

Fixed padding and margins

---

docs/_includes/explain.html
docs/_sass/explain.scss

The images in the distributed performance management were not in the correct state.
- Updated images and styles
Let me know if there are any changes need to make. Thank you.

[Site] Updated images in Distributed Performance Management Section

---

docs/_includes/faq.html
docs/_layouts/docs.html
docs/_sass/getnighthawk.scss

This PR fixes two issues.
- Before Changes
https://user-images.githubusercontent.com/58226527/121772753-13f01980-cb95-11eb-913d-5c3940fa82e1.mp4
https://user-images.githubusercontent.com/58226527/121772758-1ce0eb00-cb95-11eb-9382-9290b2d2d36e.mp4
- After Changes 
https://user-images.githubusercontent.com/58226527/121772766-2cf8ca80-cb95-11eb-9126-9a6f41ffa24e.mp4
https://user-images.githubusercontent.com/58226527/121772767-2f5b2480-cb95-11eb-89cb-78bb996b4eac.mp4
- Before Changes
https://user-images.githubusercontent.com/58226527/121772793-51ed3d80-cb95-11eb-8328-c6eb9e625fc1.mp4
- After Changes
https://user-images.githubusercontent.com/58226527/121772824-9973c980-cb95-11eb-9840-e6633e0b3576.mp4
Let me know if there are any other changes we can …

[Site] Fixed Dropdown Close Issue --signoff

---

.github/workflows/invitations.yml

Signed-off-by: Jashpatel1 <patel.5@iitj.ac.in>
This PR adds invitation workflow for getnighthawk.

Added invitation workflow

---

docs/_sass/footer.scss
docs/_sass/getnighthawk.scss

- Updated footer ul style
Let me know if there are any other changes we can make. Thank you.

[Site] Updated Footer ul style --signoff

---

docs/_sass/getnighthawk.scss
docs/index.html
docs/pages/about.html

This PR fixes #138 
The current logo on the Getnighthawk home page is the same as the navbar logo. 
- Updated Home logo for desktop
- Updated Styles for smaller devices

[Site] Updated home page logo

---

docs/_sass/footer.scss
docs/_sass/getnighthawk.scss

Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>
Updated the site home page according to the figma design.
This PR fixes #142 

Updated the site home page

---

docs/_sass/getnighthawk.scss
docs/pages/docs.html

[Site] Updated Docs Logo and Para Style

---

docs/_sass/mailing-list.scss

Added hover effects on mailing list buttons for a better UI experience.
https://user-images.githubusercontent.com/58226527/122771077-b6aa4580-d2c3-11eb-8088-c731ca2babb4.mp4
https://user-images.githubusercontent.com/58226527/122771104-bd38bd00-d2c3-11eb-82b3-427891cd387c.mp4

[Site] Added hover effects on mailing list buttons

---

docs/_sass/about.scss
docs/pages/about.html

There was an issue with about section responsiveness on smaller screens/
- Aligned text in the center
- Add Margins around divs

[Site] Fixed about page responsive issue --signoff

---

README.md

Add Discussion Forum Link in ReadMe issue#148

---

docs/_includes/getnighthawk.html
docs/_sass/getnighthawk-purpose.scss

- Fixed responsiveness issues in the purpose section
This PR fixes #153 

[Site] Fixed Purpose Section Issues

---

.github/workflows/slack.yml

Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>
Tried fixing the workflow to count the stars on getnighthawk on slack

fixed slack star workflow

---

docs/_sass/getnighthawk.scss
docs/pages/docs.html

- There were some responsiveness issues on the docs page

[Site] Fixed Docs page responsiveness

---

docs/_sass/features.scss
docs/_sass/layout.scss
docs/collections/_pages/features.html

- Fixed Features Page styling
- Linked `Get Started` button to a correct section in docs for users to read more about it 
- Took reference of PR's made for features page in meshery.io

[Site] Fixed Features Page

---

docs/_sass/getnighthawk.scss
docs/index.html

Signed-off-by: AnshumanDhiman <67755381+AnshumanDhiman@users.noreply.github.com>
Added padding and center aligned text for mobile viewers
This PR fixes #173 

Added mobile responsiveness for Paragraphs w/signoff

---

.github/ISSUE_TEMPLATE/site_update.md

Comments out the description in the issue template.

Comments out the the description in the issue template

---

docs/pages/about.html

Signed-off-by: Zain-Muiz <zainu10863@gmail.com>
The current data on the page explaining "What is nighthawk" and "Why get nighthawk" are same.
This PR fixes #162 

Updated about page

---

.github/label-commenter-config.yml

Signed-off-by: amino19 <anshumaankrprasad76@gmail.com>
CI Workflow for `Label Commenter` is failing, refixed indentation.
This PR fixes #180 #181 
@navendu-pottekkat & @warunicorn19: Sorry for the inconvenience caused, this pull request will fix it!

[Refix] Label Commenter Workflow

---

docs/_sass/getnighthawk.scss

Signed-off-by: Tothagata <tothagata.bhattacharjee@gmail.com>
Added min-height=100vh for the content-box.
This PR fixes #183 

Update Docs Content Box CSS

---

docs/_sass/about.scss

Signed-off-by: AnshumanDhiman <67755381+AnshumanDhiman@users.noreply.github.com>
This PR fixes #188 

Added responsiveness to the latency scale image w/signoff

---

README.md

Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>
This PR removes references to GetNighthawk.

[Docs] Remove GetNighthawk Reference

---

.github/workflows/build-and-publish.yaml

This PR fixes the build and release workflow.

Add token to authenticate git commands

---

.github/workflows/build-and-publish.yaml

Use "main" branch from Nighthawk as they are not making releases and this also fixes an improper ref in the checkout action.

Checkout main branch in Nighthawk

---

scripts/setup.sh

This PR updates installation of Bazel for macOS and Ubuntu and also bumps the version of Bazel used by default.

Update setting up Bazel and bump to latest version

---

docs/_sass/faq.scss

Signed-off-by: Rehane <abusayid693@gmail.com>
This PR fixes #216 

Vertical whitespace in faq

---

.github/workflows/slack.yml

Signed-off-by: Fidal <fidal15perfect@gmail.com>
This PR fixes #224 

Update slack.yml workflow

---

.github/workflows/newcomer-alert.yml

Signed-off-by: Jerod Culpepper cpepper96@gmail.com
This PR fixes #221

added newcomer-alert yml file

---

docs/_includes/faq.html
docs/_sass/footer.scss
docs/_sass/getnighthawk.scss
docs/_sass/mailing-list.scss
docs/_sass/navigation.scss
docs/assets/js/stellarnav.js

- Fixed `Homepage` responsiveness

[Site] Fixed Homepage responsive

---

docs/_sass/layout.scss
docs/index.html

[Site] Fixed unresponsive image

---

docs/_data/footer.yml

The broken link is fixed with the correct one #230 
Kindly review if there’s any error please let me know, Thank you.
Signed-off-by: Swapnil Bhabal (swapnilbhabal787@gmail.com)

Link in the footer is fixed successfully

---

docs/_includes/faq.html

Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>
Added more FAQs in the FAQ section 
This PR fixes #78 

Chore[Docs] : Added more FAQs

---

docs/_sass/layout.scss
docs/index.html

[Site] Fixed image skewing

---

docs/_sass/getnighthawk.scss

Signed-off-by: Akshit <akshitarora9211@gmail.com>
add `justify-content: space-between` to accordion-button class
This PR fixes #239 

[Site] add flex to `accordion-button`

---

docs/collections/_docs/adaptive_load_controller.md

Signed-off-by: Sunny Kumar <sunny514173@gmail.com>
This PR fixes #177 

add Adaptive Load Controller deck

---

docs/_data/docs.yml
docs/_layouts/docs.html
docs/assets/css/sidebar_doc.css
docs/assets/js/docs_nav.js
docs/collections/_docs/adaptive_load_controller.md
docs/collections/_docs/functionality/performance-benchmarking.md
docs/pages/docs.html

Signed-off-by: Sunny Kumar <sunny514173@gmail.com>
Changed navigation on the documentation page.
This PR fixes #88
Added a floating navigation button for smaller screens.
Changed the styles of navigation on docs.
Added the responsive design to adaptive load controller slides.

add float navigation to docs

---

docs/_layouts/docs.html
docs/collections/_docs/architecture/nighthawk-architecture.md
docs/pages/docs.html

Signed-off-by: Sonichigo <kurosakiichigo.songoku@gmail.com>
This PR fixes #249 
The issue was created in docs/_layout/docs.html part due to {{ foo }} above the {{content}}

[FIX] Foo Issue removed

---

docs/assets/css/sidebar_doc.css

Signed-off-by: Ritesh Karankal <ritesh.karankal200@gmail.com>
This PR fixes #252 

Make sidebar sticky w/signoff

---

docs/_includes/footer.html

Signed-off-by: Axit Patel <patelakshit2025@gmail.com>
This PR fixes #260 
I have automate the year in the footer section

updated year

---

docs/assets/css/sidebar_doc.css

Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>
Fixed Sidebar in mobile view, made it rectangle and placed it to the edge 
This PR fixes #254 

Issue-254 (Chore): Fixed Sidebar in mobile view

---

pkg/client/transform.go
pkg/proto/fortio.pb.go

change from int32 to string

---

pkg/proto/fortio.pb.go

fix prototag

---

sample_data/sample_data.json

Test release drafter

---

pkg/client/transform.go

add support for labels

---

README.md

sharmaaryan9837@gmail.com
This PR fixes #301 
- [ x ] Yes, I signed my commits.

#301 Fixed Community welcome link Signed-off-by: Aryan Sharma <sharmaaryan9837@gmail.com>

---

docs/_includes/analytics.html
docs/_includes/header.html
docs/_layouts/default.html

Setup google tag manager for nighthawk website

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/site_update.md

feat: updated issue template

---

.github/PULL_REQUEST_TEMPLATE.md

Redirected to right address

---

CONTRIBUTING.md

This PR fixes #344 
**[Signed commits](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

[Fix] Broken Link in Contributing.md
