docs/index.html
Added the missing component on the homepage under the herosection
This PR fixes #63
=> upadetd the missing component on herosection

docs/_sass/getnighthawk.scss, docs/index.html
Updated the 'why-getnighthawk' section according to the Figma mockup.
This PR fixes #72 
=> Why getnighthawk section fixes

docs/_includes/mailing-list.html, docs/_sass/mailing-list.scss, docs/assets/css/main.scss, docs/index.html
Signed-off-by: Akash Hadagali <akashc777@gmail.com>
This PR fixes #101 
=> added mailing list

docs/_sass/getnighthawk.scss, docs/pages/docs.html
- There was an issue with section padding on the docs page.
- Added padding around the links
Let me know if we can make any other changes. Thank you.
=> [Site] Fixed docs section padding

docs/_sass/getnighthawk.scss, docs/pages/docs.html
Updated style and color of docs section.
This PR fixes #124 
Let me know if there are any other changes or fixes we can make.
=> [Site] Updated docs section style

docs/_sass/getnighthawk-purpose.scss
There was an issue with the alignment of the list in the "Purpose Of GetNighthawk" section.
- Updated alignment
Let me know if there are any other changes we can make. Thank you.
=> [Site] Fixed purpose section list alignment --signoff

docs/_sass/getnighthawk.scss
There was an issue with padding around the content on the docs page.
Let me know if there are any other changes we can make. Thank you.
=> [Site] Fixed padding around docs content --signoff

docs/_sass/faq.scss
This PR fixes #137 
In the current state, The FAQs answers are a bit light and difficult to read on the white background.
- Updated font size and color of the FAQs answers.
Let me if there are any other changes we can make.
=> [Site] Improved legibility of Answers test in FAQs

docs/_layouts/page.html, docs/_sass/features.scss, docs/_sass/footer.scss
- There is an issue in the footer on the features page as the social icons are not properly aligned
<h3>Screenshots</h3>
- Fixed the alignment of the social icons
<h3>Screenshots</h3>
=> [Site] Fixed Features Page SI Footer

docs/_layouts/docs.html, docs/_sass/getnighthawk.scss
- There were some responsive issues in the docs section 1/overview page
=> [Site] Fixed Docs Section 1/Overview Responsiveness

docs/_sass/explain.scss, docs/_sass/faq.scss, docs/_sass/getnighthawk.scss
- There were several areas where the fonts are large for mobile screens
=> [Site]Fixed Home Page Lg Font Issues

docs/_sass/getnighthawk.scss, docs/index.html
Added responsive heading and paragraph in the Index page so that when user view in the mobile view heading and paragraph automatically changes to center align
Signed-off-by: AnshumanDhiman <67755381+AnshumanDhiman@users.noreply.github.com>
This PR fixes #168 
=> Added responsive heading and paragraph

docs/_includes/stewarded.html
Signed-off-by: afzal442 <afzal442@gmail.com>
Adds the missing links to each image on the front page
=> Added the missing links to each img on the front page

docs/_sass/landing-page.scss, docs/assets/js/main.js, docs/index.html
Signed-off-by: afzal442 <afzal442@gmail.com>
Adds scroll to Up button
=> Added scroll to Up button

README.md
Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>
This PR updates the NightHawk description.
=> [Docs] Update Nighthawk Description

docs/_includes/subscribe.html, docs/assets/css/subscribe.css, docs/collections/_pages/subscribe.html
Signed-off-by: Abhijay Jain <Abhijay007j@gmail.com>
Formatted community Mailing list component
This PR fixes #229 
=> Chore: Formatted community Mailing list component

docs/assets/css/stellarnav.css
Signed-off-by: anirudh-bukka <anirudh.bukka@gmail.com>
This PR fixes #189 
Added hover effects and corrected the position of the drop down menu list from the hamburger button.
=> chore:Added responsive Navbar

docs/_sass/index.scss, docs/_sass/layout.scss, docs/index.html
Signed-off-by: Akshit <akshitarora9211@gmail.com>
The meshery nighthawk performance chart image is not 50% of its container.
This PR fixes #206 
=> [site] image container size to 50%

WORKSPACE
This PR adds a WORKSPACE for running Bazel commands for custom Nighthawk builds.
Related to https://github.com/layer5io/getnighthawk/pull/247
=> Add WORKSPACE file for running Bazel commands

docs/_layouts/docs.html, docs/assets/css/copy-button.css, docs/assets/css/getnighthawk.css, docs/assets/css/main.scss
this PR adds a copy-button icon to code blocks in documentation
This PR fixes #337 
I have added the button using javascript dom manipulation by searching all the code blocks and
adding the button to them in the code and than there is a CSS file for button, and also imported clipboard.min.js for copy function.
https://github.com/layer5io/getnighthawk/assets/64972958/b5590516-8114-4d19-8ba8-4cd831d987b7
**[Signed commits](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
=> added copy button issue 337 omesh-omg
